version: "3.8"

services:
  database:
    image: mariadb:10.5
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: panel
      MYSQL_USER: pterodactyl
      MYSQL_PASSWORD: ${DB_PASSWORD:-CHANGE_ME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-CHANGE_ME_TOO}
    volumes:
      - ./database:/var/lib/mysql
    expose:
      - "3306"
    restart: always

  cache:
    image: redis:alpine
    restart: always

  panel:
    image: ghcr.io/pterodactyl/panel:latest
    depends_on:
      - database
      - cache
    ports:
      - "80:80"
      # If you terminate TLS here, also map 443
      # - "443:443"
    environment:
      APP_ENV: "production"
      APP_URL: ${APP_URL:-http://localhost}
      APP_TIMEZONE: "UTC"

      DB_HOST: database
      DB_PORT: "3306"
      DB_DATABASE: panel
      DB_USERNAME: pterodactyl
      DB_PASSWORD: ${DB_PASSWORD:-CHANGE_ME}

      REDIS_HOST: cache
      REDIS_PORT: "6379"
      QUEUE_CONNECTION: "redis"
      SESSION_DRIVER: "redis"
      CACHE_DRIVER: "redis"

      # Optional mail config (set these if you want email)
      # MAIL_MAILER: smtp
      # MAIL_HOST: smtp.example.com
      # MAIL_PORT: "587"
      # MAIL_USERNAME: user@example.com
      # MAIL_PASSWORD: yourpassword
      # MAIL_ENCRYPTION: tls
      # MAIL_FROM_ADDRESS: panel@example.com
      # MAIL_FROM_NAME: "Pterodactyl Panel"

      TRUSTED_PROXIES: "*"
    volumes:
      - ./var:/app/var
      - ./nginx:/etc/nginx/http.d
      - ./certs:/etc/letsencrypt
    restart: always
